import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Lateralheader from '@/components/Element/Lateralheader'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,
}: {
  children: React.ReactNode
}) {

  

  return (
    <html lang="en">
    
      <body className={inter.className}>

      <div
  className="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
        <Lateralheader/>
   
        
        {children}
      

      </body>

    </html>
  )
}
